Add parameter LimitResultPerPart to filter classes
ZEISS-PiWeb/PiWeb-Api pull request #108
Opened 2021-08-27 07:10 UTC by czthiele

New parameter for measurement search: LimitResultPerPart.
- in combination with a part path and deep this will trigger a search for all child parts and return the specified amount of measurements per part
- in combination with a list of part uuids this will return the specified amount of measurements per part uuid

2021-08-31 13:08 UTC, czkum requested changes

2021-09-01 06:13 UTC, czthiele commented on src/Api.Rest/Contracts/DataServiceFeatureMatrix.cs
> +		//Request a limit per part when fetching measurements.
Done

2021-09-01 06:14 UTC, czthiele commented on src/Api.Rest/HttpClient/Data/DataServiceRestClient.cs
> +		private async Task CheckLimitResultPerPartFeatureSupport( AbstractMeasurementFilterAttributesDto filter, CancellationToken cancellationToken )
Good point, I changed the FeatureMatrix check methods to this name pattern.

2021-09-01 06:16 UTC, czthiele commented on src/Api.Rest/HttpClient/Data/DataServiceRestClient.cs
> +			await CheckLimitResultPerPartFeatureSupport( filter, cancellationToken );
I have moved all "feature checks" to separate methods which makes the code more readable.

2021-09-01 06:16 UTC, czthiele commented on src/Api.Rest/HttpClient/Data/DataServiceRestClient.cs
> +			await CheckLimitResultPerPartFeatureSupport( filter, cancellationToken );
Done

2021-09-01 06:16 UTC, czthiele commented on src/Api.Rest/HttpClient/Data/DataServiceRestClient.cs
> +			await CheckLimitResultPerPartFeatureSupport( filter, cancellationToken );
Done

2021-09-01 06:35 UTC, merged